sonar.projectKey=pi-fence
sonar.projectName=pi-fence
sonar.sourceEncoding=UTF-8

sonar.sources=extensions,scripts
sonar.tests=tests

sonar.exclusions=node_modules/**,dist/**,scripts/out/**
sonar.test.inclusions=tests/**/*.ts
sonar.typescript.tsconfigPath=tsconfig.json
